### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by BDonnot** [BDonnot/lightsim2grid#84]
- [ ] possibility to change transformer tap ratio
- [ ] distributed slack for other PF algo see #73 
- [ ] solver for hybrid AC / DC grid #81 

For later (when I have time or if someone is willing to help) :

- [ ] HELM powerflow #17 
- [ ] TDPF #40
